---
# Source: reflector-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector-reflector-chart
  labels:

    helm.sh/chart: reflector-chart-0.1.0
    app.kubernetes.io/name: reflector-chart
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: reflector-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: reflector
spec:
  selector:
    app: reflector-deploy
  ports:
    - port: 80
      targetPort: 5000
---
# Source: reflector-chart/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reflector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reflector-deploy
    spec:
      containers:
        - name: reflector-server
          image: marcecaro/reflector@sha256:e26568fd7cdbbac891bb834280cd91aaf39b390290f13876feeb8d4886c09f00
          imagePullPolicy: Always
          # ports:
          # - containerPort: 5000
---
# Source: reflector-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: reflector
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /reflector
        backend:
          serviceName: reflector
          servicePort: 80
