---
# Source: echo-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-echo-chart
  labels:

    helm.sh/chart: echo-chart-0.1.0
    app.kubernetes.io/name: echo-chart
    app.kubernetes.io/instance: echo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: echo-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo-deploy
  ports:
    - port: 80
      targetPort: 5000
---
# Source: echo-chart/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-deploy
    spec:
      containers:
        - name: echo-server
          image: marcecaro/echo@sha256:e80c15342330af01131d39caf09e5ba7267bf3de4b075a0e7abc25832849bdac
          imagePullPolicy: Always
          # ports:
          # - containerPort: 5000
---
# Source: echo-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /echo
        backend:
          serviceName: echo
          servicePort: 80
